### ISSUE TITLE
Memory option is not working for other language

### ISSUE THREAD

**Issue by killajoe** [mrgreen3/beerfetch#2]
echo -e "\e[32mMemory: \e[0m$(free -h | awk '/^Mem/ {print $2}')gs"

German (great in Beer) shows like so:

![Screenshot_20240503_130443](https://github.com/mrgreen3/beerfetch/assets/16797647/f79916ad-49fa-45a6-a976-bb38224c2abb)

**Comment by mrgreen3** [comment]
Switched to using -g instead of -h ;-)
